# Generated by Django 6.0.1 on 2026-01-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
